- name: Install required packages
  yum:
    name:
      - python3
      - sqlite
    state: present

- name: Install Flask
  pip:
    name: flask

- name: Upload application code
  copy:
    src: app.py
    dest: /opt/noteapp/app.py
    mode: '0755'

- name: Upload systemd service
  copy:
    src: noteapp.service
    dest: /etc/systemd/system/noteapp.service

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start the note-taking app service
  systemd:
    name: noteapp
    enabled: yes
    state: started

- name: Create app directory
  file:
    path: /opt/noteapp
    state: directory
    owner: ec2-user
    group: ec2-user

- name: Create templates directory
  file:
    path: /opt/noteapp/templates
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Upload app.py
  copy:
    src: app.py
    dest: /opt/noteapp/app.py
    mode: '0755'

- name: Upload HTML template
  copy:  # or 'template:' if you're using .j2 + {% raw %}
    src: index.html
    dest: /opt/noteapp/templates/index.html
    mode: '0644'

